export const DO_ADDPRODUCT = 'DO_ADDPRODUCT'
export const DO_DELETEPRODUCT = 'DO_DELETEPRODUCT'
export const DO_UPDATEPRODUCT = 'DO_UPDATEPRODUCT'
export const DO_GETPRODUCTS = 'DO_GETPRODUCTS'
export const DO_GETPRODUCT = 'DO_GETPRODUCT'
export const LOAD_NEW_PRODUCT = "LOAD_NEW_PRODUCT"
export const DO_UPDATEFIELD = "DO_UPDATEFIELD"